{include file = 'templates/header.tpl'}
<tbody>
    <table>
        <tr>
            <th>
            </th>
            <th>
            </th>
        </tr>
        <tr>
            <td>
            </td>
            <td>
            </td>
        </tr>
    </table>
</tbody>

<tbody>
    <table>
        <tr>
            <th>
            </th>
            <th>
            </th>
            <th>
            </th>
            <th>
            </th>
            <th>
            </th>
        </tr>
        <tr>
            <td>
            </td>
            <td>
            </td>
            <td>
            </td>
            <td>
            </td>
            <td>
            </td>
        </tr>
    </table>
</tbody>
{include file = 'templates/footer.tpl'}